import { Inter } from "next/font/google";
import "../globals.css";
import {NextIntlClientProvider, useMessages} from "next-intl";
import {ThemeProvider} from "@mui/material";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import themeClassic from "@/themes/classic";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children, params }) {
    const messages = useMessages();

    return (
        <html lang={params.lang}>
            <NextIntlClientProvider messages={messages}>
                <body className={inter.className}>
                    <AppRouterCacheProvider>
                        <ThemeProvider theme={themeClassic}>
                                <main className='wrapper'>{children}</main>
                        </ThemeProvider>
                    </AppRouterCacheProvider>
                </body>
            </NextIntlClientProvider>
        </html>
    );
}
