import "../globals.css";
import {NextIntlClientProvider, useMessages} from "next-intl";
import {ThemeProvider} from "@mui/material";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import themeClassic from "@/themes/classic";
import ReduxProvider from "@/store/redux-provider";
import {Poppins, Sen} from "next/font/google";

const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

const sen = Sen({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
});

const fonts = {poppins, sen}

export const metadata = {
  title: "Food Delivery",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({children, params}) {
  const messages = useMessages();

  return (
    <html lang={params.lang}>
    <NextIntlClientProvider messages={messages}>
      <body className={sen.className}>
      <AppRouterCacheProvider>
        <ThemeProvider theme={themeClassic}>
          <ReduxProvider>
            <main>{children}</main>
          </ReduxProvider>
        </ThemeProvider>
      </AppRouterCacheProvider>
      </body>
    </NextIntlClientProvider>
    </html>
  );
}